### ISSUE TITLE
Is it not complete?

### ISSUE THREAD

**Issue by GallonDeng** [bebosudo/HR-estimation-CVPR2016#2]
Hi, the performance in the paper looks good and it is very interesting.  I am also trying to reimplement it. How about your work on this?

**Comment by bebosudo** [comment]
Hi @AllenDun, the paper is interesting, but we didn't implement the final part of the application of the filter, because the original author of the paper didn't explain very well how to create it, and we didn't have the knowledge to understand that part.

This project is MIT licensed, so feel free to use whatever you find in it. If you manage to implement the paper and you publish your code, please ping me, because I'd love to try the whole implementation.

If you have any doubt or want suggestions, feel free to ping me, either on this repo or at my contacts.
